import { SlashCommandBuilder, PermissionFlagsBits, ChannelType } from 'discord.js';
import type { Command } from '../handlers/Command.js'; import { Warn } from '../models/Warn.js'; import { embed } from '../utils/embeds.js'; import { COLORS } from '../config/constants.js'; import { canModerate, P } from '../utils/permissions.js'; import { log } from '../utils/logger.js';

const data = new SlashCommandBuilder().setName('moderation').setDescription('Commandes de modération (utiliser les sous-commandes)')
  .addSubcommand(s => s.setName('ban').setDescription('Bannir').addUserOption(o=>o.setName('membre').setDescription('Membre').setRequired(true)).addStringOption(o=>o.setName('raison').setDescription('Raison')))
  .addSubcommand(s => s.setName('tempban').setDescription('Bannir temporairement').addUserOption(o=>o.setName('membre').setDescription('Membre').setRequired(true)).addIntegerOption(o=>o.setName('jours').setDescription('Jours').setRequired(true)).addStringOption(o=>o.setName('raison').setDescription('Raison')))
  .addSubcommand(s => s.setName('unban').setDescription('Débannir').addStringOption(o=>o.setName('utilisateur_id').setDescription('ID utilisateur').setRequired(true)).addStringOption(o=>o.setName('raison').setDescription('Raison')))
  .addSubcommand(s => s.setName('kick').setDescription('Expulser').addUserOption(o=>o.setName('membre').setDescription('Membre').setRequired(true)).addStringOption(o=>o.setName('raison').setDescription('Raison')))
  .addSubcommand(s => s.setName('timeout').setDescription('Timeout').addUserOption(o=>o.setName('membre').setDescription('Membre').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Minutes').setRequired(true)).addStringOption(o=>o.setName('raison').setDescription('Raison')))
  .addSubcommand(s => s.setName('untimeout').setDescription('Retirer un timeout').addUserOption(o=>o.setName('membre').setDescription('Membre').setRequired(true)))
  .addSubcommand(s => s.setName('mute').setDescription('Alias de timeout').addUserOption(o=>o.setName('membre').setDescription('Membre').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Minutes').setRequired(true)))
  .addSubcommand(s => s.setName('warn').setDescription('Avertir').addUserOption(o=>o.setName('membre').setDescription('Membre').setRequired(true)).addStringOption(o=>o.setName('raison').setDescription('Raison').setRequired(true)))
  .addSubcommand(s => s.setName('warns').setDescription('Voir les avertissements').addUserOption(o=>o.setName('membre').setDescription('Membre').setRequired(true)))
  .addSubcommand(s => s.setName('unwarn').setDescription('Retirer un avertissement').addStringOption(o=>o.setName('identifiant').setDescription('ID warn').setRequired(true)))
  .addSubcommand(s => s.setName('clear').setDescription('Supprimer des messages').addIntegerOption(o=>o.setName('nombre').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true)))
  .addSubcommand(s => s.setName('slowmode').setDescription('Ralentir un salon').addIntegerOption(o=>o.setName('secondes').setDescription('0-21600').setMinValue(0).setMaxValue(21600).setRequired(true)))
  .addSubcommand(s => s.setName('lock').setDescription('Verrouiller le salon'))
  .addSubcommand(s => s.setName('unlock').setDescription('Déverrouiller le salon'));

export default { data, async execute(i) {
  if (!i.guild) return void await i.reply({ content: 'Serveur requis.', ephemeral: true }); const sub=i.options.getSubcommand(); const reason=i.options.getString('raison') ?? 'Aucune raison fournie';
  if (sub==='unban') { if (!i.memberPermissions?.has(P.BanMembers)) return void await i.reply({content:'Permission manquante.',ephemeral:true}); await i.guild.bans.remove(i.options.getString('utilisateur_id',true), reason); return void await i.reply({embeds:[embed('Utilisateur débanni.',COLORS.success)]}); }
  if (sub==='warns') { const u=i.options.getUser('membre',true); const warns=(await Warn.find({guildId:i.guildId!,userId:u.id})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,20); return void await i.reply({embeds:[embed(warns.length ? warns.map(w=>`\`${w.warnId}\` — ${w.reason}`).join('\n') : 'Aucun avertissement.')]}); }
  if (sub==='unwarn') { if (!i.memberPermissions?.has(P.ModerateMembers)) return void await i.reply({content:'Permission manquante.',ephemeral:true}); const warn=await Warn.findOneAndDelete({guildId:i.guildId,warnId:i.options.getString('identifiant',true)}); return void await i.reply({embeds:[embed(warn?'Avertissement supprimé.':'Avertissement introuvable.',warn?COLORS.success:COLORS.warning)]}); }
  if (sub==='clear') { if (!i.memberPermissions?.has(P.ManageMessages) || !i.channel?.isTextBased() || !('bulkDelete' in i.channel)) return void await i.reply({content:'Permission ou salon invalide.',ephemeral:true}); const n=i.options.getInteger('nombre',true); await (i.channel as any).bulkDelete(n,true); return void await i.reply({embeds:[embed(`${n} messages supprimés.`,COLORS.success)],ephemeral:true}); }
  if (sub==='slowmode'||sub==='lock'||sub==='unlock') { if (!i.memberPermissions?.has(P.ManageChannels) || !i.channel?.isTextBased() || !('setRateLimitPerUser' in i.channel)) return void await i.reply({content:'Permission ou salon invalide.',ephemeral:true}); if(sub==='slowmode') await (i.channel as any).setRateLimitPerUser(i.options.getInteger('secondes',true)); else await (i.channel as any).permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:sub==='unlock'}); return void await i.reply({embeds:[embed(sub==='lock'?'Salon verrouillé.':sub==='unlock'?'Salon déverrouillé.':'Slowmode mis à jour.',COLORS.success)]}); }
  const user=i.options.getUser('membre',true); const target=await i.guild.members.fetch(user.id).catch(()=>null); if(!target) return void await i.reply({content:'Membre introuvable.',ephemeral:true}); const permission=(sub==='ban'||sub==='tempban'?P.BanMembers:sub==='kick'?P.KickMembers:P.ModerateMembers); if(!await canModerate(i,target,permission)) return;
  if(sub==='warn') { const warnId=`W-${Date.now().toString(36).toUpperCase()}`; await Warn.create({guildId:i.guildId,userId:user.id,moderatorId:i.user.id,reason,warnId}); await i.reply({embeds:[embed(`${user} averti — \`${warnId}\`.`,COLORS.warning)]}); await log(i.client,i.guild,'Warn',`${user.tag}: ${reason}`,COLORS.warning); return; }
  if(sub==='ban'||sub==='tempban') await target.ban({reason}); else if(sub==='kick') await target.kick(reason); else if(sub==='untimeout') await target.timeout(null,reason); else await target.timeout(i.options.getInteger('minutes',true)*60_000,reason);
  await i.reply({embeds:[embed(`${user} : action **${sub}** exécutée.`,COLORS.success)]}); await log(i.client,i.guild,'Modération',`${sub} — ${user.tag}: ${reason}`,COLORS.success);
} } satisfies Command;
